
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% email
%
% File for sending e-mail messages. M-file consists of an external function
% that does not provide an output parameter. It requires the input
% parameter 'id' which contains the identifier of the error message being
% sent.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function email(id)

%{
    Gmail credentials
    - requires:
        - source        - sender's email
        - password      - sender's password
        - destination   - recipient's email
%}
source = 'Vesna.STU.2021@gmail.com';
destination = 'dodoodod1221@gmail.com';
password = 'Sklenik2022';

% Set up Gmail SMTP
setpref('Internet','E_mail',source);
setpref('Internet','SMTP_Server','smtp.gmail.com');
setpref('Internet','SMTP_Username',source);
setpref('Internet','SMTP_Password',password);

% Gmail server
props = java.lang.System.getProperties;
props.setProperty('mail.smtp.auth','true');
props.setProperty('mail.smtp.socketFactory.class', 'javax.net.ssl.SSLSocketFactory');
props.setProperty('mail.smtp.socketFactory.port','465');

% Message description
keySet = {'connect', ...
          'email', ...
          'light', ...
          'lighting', ...
          'door', ...
          'heating', ...
          'pump', ...
          'fan', ...
          'tempT', ...
          'tempB', ...
          'bmmeH', ...
          'dhtH'};
valueSet1 = {'Arduino Cloud Connection Error', ... 
    '...', ...
    'Light Error', ...
    'Lighting Error', ...
    'Door Error', ...
    'Heating Error', ...
    'Pump Error', ...
    'Fan Error', ...
    'Top Temperature Error', ...
    'Bottom Temperature Error', ...
    'BMME Humidity Error', ...
    'DHT Humidity Error'};
valueSet2 = {'Connection to Arduino Cloud failed - no server response. New connection to the server is required.', ...
    '...', ...
    'Unable to load/send light intensity data from/to Cloud. Check connection, Arduino Cloud or lighting power supply.', ...
    'Unable to load/send lighting power supply data from/to Cloud. Check connection, Arduino Cloud or lighting power supply.', ...
    'Unable to load/send door position data from/to Cloud. Check connection, Arduino Cloud or door sensor.', ...
    'Unable to load/send heating power supply data from/to Cloud. Check connection, Arduino Cloud or heating power supply.', ...
    'Unable to load/send pump power supply data from/to Cloud. Check connection, Arduino Cloud or pump power supply.', ...
    'Unable to load/send fan power supply data from/to Cloud. Check connection, Arduino Cloud or fan power supply.', ...
    'Unable to load/send top temperature data from/to Cloud. Check connection, Arduino Cloud or temperature sensor.', ...
    'Unable to load/send bottom temperature data from/to Cloud. Check connection, Arduino Cloud or temperature sensor.', ...
    'Unable to load/send BMME humidity data from/to Cloud. Check connection, Arduino Cloud or BMME sensor.', ...
    'Unable to load/send DHT humidity data from/to Cloud. Check connection, Arduino Cloud or DHT sensor.'};

subj = containers.Map(keySet,valueSet1);
msg = containers.Map(keySet,valueSet2);

% Send email
try
    sendmail(destination,subj(id),msg(id));
    fprintf('Error notification email was sent to your mail address.\n\n')
catch
    errors('email');
end
