
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% errors
%
% Vesna control error detection file. M-file consists of an external
% function that provides 'options' an output parameter. It requires
% an input parameter 'id' which contains the identifier of the error that
% occurred during the control. The error message is displayed in the MATLAB
% Command Window. A notification email with a description of the error is
% sent to the admin's email. Many errors are associated with the connection
% to the Arduino Cloud, therefore, the connection is restored as
% a precaution.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function options = errors(id,spec)

% Error description
keySet = {'connect', ...
          'email', ...
          'light', ...
          'lighting', ...
          'door', ...
          'heating', ...
          'pump', ...
          'fan', ...
          'tempT', ...
          'tempB', ...
          'bmmeH', ...
          'dhtH'};
valueSet1 = {'Arduino API Cloud Connection', ...
    'Email', ...
    'Light', ...
    'Lighting', ...
    'Door', ...
    'Heating', ...
    'Pump', ...
    'Fan', ...
    'Top Temperature', ...
    'Bottom Temperature', ...
    'BMME Humidity', ...
    'DHT Humidity'};
valueSet2 = {'connect to Arduino API Cloud.', ...
    'send an error notification by e-mail. Check the senderʼs credentials and recipientʼs address.', ...
    'load/send light intensity data from/to Cloud.', ...
    'load/send lighting power supply from/to Cloud.', ...
    'load/send door position data from/to Cloud.', ...
    'load/send heating power supply from/to Cloud.', ...
    'load/send pump power supply from/to Cloud.', ...
    'load/send fan power supply from/to Cloud.', ...
    'load/send top temperature data from/to Cloud.', ...
    'load/send bottom temperature data from/to Cloud.', ...
    'load/send BMME humidity data from/to Cloud.', ...
    'load/send DHT humidity data from/to Cloud.'};

eType = containers.Map(keySet,valueSet1);
eMessage = containers.Map(keySet,valueSet2);

% Error display
fprintf(2,strcat(eType(id),' Error','\nUnable to ',eMessage(id),'\n\n'))

% Send mail notification troubleshooting
if ~strcmp(id,'email')

    % Send mail notification after each 5 unsuccessful attempts
    if ~mod(spec,5)
        email(id)

        % Reconnect to Arduino API Cloud
        if ~strcmp(id,'connect')
            options = reconnect;
        end
    end
end

end
